---
- name: "jtprogru.install_atop | install packages"
  ansible.builtin.package:
    name: "{{ atop_packages }}"
    state: present
  tags: [ "install_atop" ]

- name: "jtprogru.install_atop | enable autostart"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  when: not ansible_check_mode
  with_items:
    - "atop.service"
    - "atopacct.service"
  tags: [ "install_atop" ]

- name: "jtprogru.install_atop | generate default config for atop"
  ansible.builtin.template:
    src: "atop.daily.j2"
    dest: "{{ install_atop_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: atop listner
  tags: [ "install_atop" ]
